version: "3.9"
volumes:
  db-store:
services:
  web:
    image: nginx:1.21.6-alpine
    ports:
      - 34251:80
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  app:
    build: ./docker/php
    volumes:
      - ./src:/var/www
    links:
      - db
    depends_on:
      - db
  db:
    image: mysql:8.0.26
    platform: "linux/amd64"
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - db-store:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: sample
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      TZ: "Asia/Tokyo"
  phpmyadmin:
    image: phpmyadmin
    # links:
    #   - mysql
    ports:
      - 8080:80
    volumes:
      - /sessions
    environment:
      - PMA_ARBITRARY=1
      - PMA_DATABASE=sample
      - PMA_USER=user
      - PMA_PASSWORD=secret
      - PMA_ROOT_PASSWORD=secret
